### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [sehyun2727/CPP202309#2]
### 없는 파일
- challenge/week2/candy.cpp 
- challenge/week2/temperature.cpp 
- challenge/week2/temperature2.cpp 
- project/week8/mud_game.cpp
	- 위 파일 이름이나 위치를 다시 확인하세요. 해당 소스 파일 채점이 수행되지 않습니다.

### 없는 PDF 파일
- project/week8/mud_game.pdf
	- 위 파일 이름이나 위치를 다시 확인하세요. 보고서 채점이 수행되지 않습니다.

### 워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in project/week6/tic_tac_toe
    - Warning: array index 3 is past the end of the array (which contains 3 elements) [line 94]
    - Warning: array index 3 is past the end of the array (which contains 3 elements) [line 94]
        - 2차원 변수인 board의 크기는 3x3입니다. 해당 배열에 접근하기 위한 인덱스는 0,1,2 이기 때문에, 3으로 접근할 경우 없는 공간에 접근하려고 하여 문제가 생깁니다. 인덱스를 변경해주세요.

**Comment by sehyun2727** [comment]
늦게 확인하여 죄송합니다.
이슈 전부 수정하였습니다. 확인 부탁드립니다.
